In [44]:
import pandas as pd

In [45]:
customer_df = pd.read_csv('customer_data.csv')
customer_df.head()

   customer_id  customer_name gender  age              city   join_date
0          201   Ashley Silva      F   47   Lake Edwardfort  19-01-2021
1          202  Ethan Shannon      F   55        Jaredshire  10-05-2021
2          203  Colleen Lopez      M   31        South Eric  18-07-2023
3          204   Sarah Nguyen      F   52  South Wendyhaven  23-01-2020
4          205      Eric Ruiz      M   61        North Mark  19-05-2020

In [47]:
customer_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    100 non-null    int64
 1   customer_name  100 non-null    str
 2   gender         100 non-null    str
 3   age            100 non-null    int64
 4   city           100 non-null    str
 5   join_date      100 non-null    str
dtypes: int64(2), str(4)
memory usage: 4.8 KB

In [48]:
customer_df = customer_df.drop_duplicates().reset_index(drop=True)
customer_df.head()

   customer_id  customer_name gender  age              city   join_date
0          201   Ashley Silva      F   47   Lake Edwardfort  19-01-2021
1          202  Ethan Shannon      F   55        Jaredshire  10-05-2021
2          203  Colleen Lopez      M   31        South Eric  18-07-2023
3          204   Sarah Nguyen      F   52  South Wendyhaven  23-01-2020
4          205      Eric Ruiz      M   61        North Mark  19-05-2020

In [49]:
sales_df = pd.read_csv('sales.csv')
sales_df.head()

,sale_id,product_id,customer_id,quantity_sold,sale_amount,sale_date,region
0,1,107,273,5,1000,01-09-2024,South
1,2,104,212,7,700,31-05-2024,West
2,3,107,223,2,400,19-03-2024,West
3,4,103,288,1,240,21-02-2024,West
4,5,112,274,6,600,05-05-2024,West

In [50]:
sales_df.columns = sales_df.columns.str.strip().str.lower()
sales_df.head()

,sale_id,product_id,customer_id,quantity_sold,sale_amount,sale_date,region
0,1,107,273,5,1000,01-09-2024,South
1,2,104,212,7,700,31-05-2024,West
2,3,107,223,2,400,19-03-2024,West
3,4,103,288,1,240,21-02-2024,West
4,5,112,274,6,600,05-05-2024,West

In [51]:
sales_df['quantity_sold'] = pd.to_numeric(sales_df['quantity_sold'], errors='coerce')
sales_df = sales_df.dropna(subset=['quantity_sold']).reset_index(drop=True)
sales_df['quantity_sold'] = sales_df['quantity_sold'].astype(int)
sales_df.dtypes

sale_id          int64
product_id       int64
customer_id      int64
quantity_sold    int64
sale_amount      int64
sale_date          str
region             str
dtype: object

In [52]:
product_df = pd.read_csv('product.csv')
product_df.columns = product_df.columns.str.strip().str.lower()
product_df.head()

   product_id  product_name     category  price
0         101        Laptop  Electronics    250
1         102    Smartphone  Electronics    300
2         103        Tablet  Electronics    240
3         104    Headphones  Electronics    100
4         105  Office Chair    Furniture    400

In [54]:
product_df = product_df.drop_duplicates(subset=['product_id']).reset_index(drop=True)
product_df = product_df.dropna(subset=['product_id', 'price']).reset_index(drop=True)
product_df['price'] = pd.to_numeric(product_df['price'], errors='coerce')
product_df.head()

   product_id  product_name     category  price
0         101        Laptop  Electronics    250
1         102    Smartphone  Electronics    300
2         103        Tablet  Electronics    240
3         104    Headphones  Electronics    100
4         105  Office Chair    Furniture    400

In [55]:
sales_df = sales_df.merge(
    product_df[['product_id', 'price']].rename(columns={'price': 'unit_price'}),
    on='product_id',
    how='left'
)
sales_df['unit_price'] = pd.to_numeric(sales_df['unit_price'], errors='coerce')
sales_df.head()

,sale_id,product_id,customer_id,quantity_sold,sale_amount,sale_date,region,unit_price
0,1,107,273,5,1000,01-09-2024,South,200
1,2,104,212,7,700,31-05-2024,West,100
2,3,107,223,2,400,19-03-2024,West,200
3,4,103,288,1,240,21-02-2024,West,240
4,5,112,274,6,600,05-05-2024,West,100

In [56]:
sales_df['total_sale_amount'] = sales_df['quantity_sold'] * sales_df['unit_price']
sales_df[['sale_id', 'product_id', 'quantity_sold', 'unit_price', 'total_sale_amount']].head()

   sale_id  product_id  quantity_sold  unit_price  total_sale_amount
0        1         107              5         200               1000
1        2         104              7         100                700
2        3         107              2         200                400
3        4         103              1         240                240
4        5         112              6         100                600

In [58]:
print('Sales shape:', sales_df.shape)
print('Missing unit_price count:', sales_df['unit_price'].isna().sum())
sales_df[['sale_id', 'product_id', 'quantity_sold', 'unit_price', 'total_sale_amount']].describe()

Sales shape: (300, 9)
Missing unit_price count: 0

          sale_id  product_id  quantity_sold  unit_price  total_sale_amount
count  300.000000  300.000000     300.000000   300.00000         300.000000
mean   150.500000  108.206667       5.510000   179.00000         983.883333
std     86.746758    4.741190       2.882869   143.56195        1033.846684
min      1.000000  101.000000       1.000000    20.00000          25.000000
25%     75.750000  104.000000       3.000000    50.00000         236.250000
50%    150.500000  107.000000       5.000000   150.00000         600.000000
75%    225.250000  113.000000       8.000000   300.00000        1500.000000
max    300.000000  116.000000      10.000000   600.00000        6000.000000

In [59]:
customer_df.to_csv('customer_data_clean.csv', index=False)
sales_df.to_csv('sales_clean.csv', index=False)
product_df.to_csv('product_clean.csv', index=False)